# Generated by Django 5.2.5 on 2026-02-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title/alt text for the image', max_length=100)),
                ('image', models.ImageField(help_text='Upload banner image (recommended size: 1200×300 or similar)', upload_to='ad_bars/')),
                ('is_active', models.BooleanField(default=True, help_text='Only active ads show')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower number = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Banner',
                'verbose_name_plural': 'Ad Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
