# Generated by Django 5.2.5 on 2026-02-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adbar',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='adbar',
            name='image',
        ),
        migrations.RemoveField(
            model_name='adbar',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='adbar',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct public URL to the banner image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adbar',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adbar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adbar',
            name='title',
            field=models.CharField(blank=True, help_text='Optional: Title/alt text', max_length=100),
        ),
    ]
