# Generated by Django 5.2.5 on 2026-02-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_adbar_options_remove_adbar_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adbar',
            options={},
        ),
        migrations.AddField(
            model_name='adbar',
            name='video_url',
            field=models.URLField(blank=True, help_text='Direct video URL (MP4, auto-plays muted)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adbar',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adbar',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
