# Generated by Django 5.2.5 on 2026-02-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='Optional: Paste a direct image URL (e.g. from Imgur or Google)', max_length=500, null=True),
        ),
    ]
