# Generated by Django 5.2.5 on 2026-02-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='fulfilled',
        ),
        migrations.AlterField(
            model_name='wish',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
