# Generated by Django 5.2.5 on 2026-02-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_remove_wish_fulfilled_alter_wish_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='is_granted',
            field=models.BooleanField(default=False, verbose_name='Granted'),
        ),
    ]
