# Generated by Django 5.2.5 on 2026-02-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0003_wish_is_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='Bank_account',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
