# Generated by Django 5.2.5 on 2026-02-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0004_wish_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='Bank_account',
        ),
        migrations.AddField(
            model_name='wish',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name (e.g., Commercial Bank of Ethiopia)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wish',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional: Share your phone number if you want direct contact (e.g., WhatsApp).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wish',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Optional: Bank account number or details if you accept direct transfers.', max_length=50, null=True),
        ),
    ]
