# Generated by Django 5.2.5 on 2026-02-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0005_remove_wish_bank_account_wish_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Optional', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional', max_length=20, null=True),
        ),
    ]
